name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cf_xarray>=0.6
  - cmocean
  - dask
  - matplotlib
  - netcdf4
  - numpy
  - pip
  - requests
  - xarray
  - xcmocean
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
